-- Up
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS item_type VARCHAR(20) DEFAULT 'car';
ALTER TABLE tags ADD COLUMN IF NOT EXISTS custom_message TEXT;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS is_paused BOOLEAN DEFAULT FALSE;

-- Down
ALTER TABLE vehicles DROP COLUMN IF EXISTS item_type;
ALTER TABLE tags DROP COLUMN IF EXISTS custom_message;
ALTER TABLE tags DROP COLUMN IF EXISTS is_paused;
